from __future__ import annotations

import argparse
import os
from pathlib import Path
from typing import Iterable


DEFAULT_PROFILE = r"D:\agent_browser_profile"
DEFAULT_COOKIE_FILE = r"C:\tmp\uav_cvgl_cookies.txt"
DEFAULT_DOWNLOAD_DIR = r"C:\tmp\uav_cvgl_downloads"


def default_profile() -> str:
    return os.getenv("UAV_CVGL_BROWSER_PROFILE", DEFAULT_PROFILE)


def default_cookie_file() -> str:
    return os.getenv("UAV_CVGL_COOKIE_FILE", DEFAULT_COOKIE_FILE)


def default_download_dir() -> str:
    return os.getenv("UAV_CVGL_DOWNLOAD_DIR", DEFAULT_DOWNLOAD_DIR)


def add_common_browser_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--profile", default=default_profile(), help="Persistent Chromium profile directory.")
    parser.add_argument("--cookie-output", default=default_cookie_file(), help="Netscape cookie export path for requests.")
    parser.add_argument("--download-dir", default=default_download_dir(), help="Browser download directory.")


def ensure_paths(profile: str, cookie_output: str | None = None, download_dir: str | None = None) -> None:
    Path(profile).mkdir(parents=True, exist_ok=True)
    if cookie_output:
        Path(cookie_output).parent.mkdir(parents=True, exist_ok=True)
    if download_dir:
        Path(download_dir).mkdir(parents=True, exist_ok=True)


def import_playwright():
    try:
        from playwright.sync_api import sync_playwright
    except ImportError as exc:
        raise SystemExit(
            "Python package 'playwright' is not installed. Install it with:\n"
            "  D:\\anaconda\\envs\\dinov3\\python.exe -m pip install playwright\n"
            "  D:\\anaconda\\envs\\dinov3\\python.exe -m playwright install chromium"
        ) from exc
    return sync_playwright


def cookie_domain(cookie: dict) -> str:
    domain = (cookie.get("domain") or "").strip()
    if not domain:
        return ""
    return domain


def export_netscape_cookies(cookies: Iterable[dict], output_path: str) -> int:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    count = 0
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by UAV-CVGL browser session helper. Keep this file private.",
    ]
    for cookie in cookies:
        domain = cookie_domain(cookie)
        name = cookie.get("name")
        if not domain or not name:
            continue
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path_value = cookie.get("path") or "/"
        secure = "TRUE" if cookie.get("secure") else "FALSE"
        expires = cookie.get("expires")
        if expires is None or float(expires) < 0:
            expires = 0
        value = cookie.get("value") or ""
        out_domain = domain
        if cookie.get("httpOnly") and not out_domain.startswith("#HttpOnly_"):
            out_domain = "#HttpOnly_" + out_domain
        lines.append("\t".join([out_domain, include_subdomains, path_value, secure, str(int(float(expires))), name, value]))
        count += 1
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return count


def print_cookie_domain_summary(cookies: Iterable[dict]) -> None:
    counts: dict[str, int] = {}
    for cookie in cookies:
        domain = cookie_domain(cookie).lstrip(".").lower()
        if domain:
            counts[domain] = counts.get(domain, 0) + 1
    print("Cookie domain summary:")
    for domain, count in sorted(counts.items(), key=lambda item: (-item[1], item[0]))[:80]:
        print(f"  {domain}: {count}")
